version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: prmanager-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prmanager
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prmanager"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator:
    image: migrate/migrate:4
    container_name: prmanager-migrator
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@db:5432/prmanager?sslmode=disable",
        "up"
      ]
    restart: "on-failure"

  app:
    build: .
    container_name: prmanager-app
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      CONFIG_PATH: /config/prod.yaml
    ports:
      - "8080:8080"

volumes:
  postgres_data:
